const BUILDINGS = [
  { id: 'tomb',       name: 'Tomb',               icon: '⚰️', desc: 'Skeletons slowly harvest souls',              baseCost: 10,         baseIncome: 0.1   },
  { id: 'dungeon',    name: 'Dungeon',             icon: '🔒', desc: 'Prisoners surrender their life force',        baseCost: 75,         baseIncome: 0.5   },
  { id: 'altar',      name: 'Dark Altar',          icon: '🕯️', desc: 'Dark rituals amplify the soul stream',        baseCost: 500,        baseIncome: 2     },
  { id: 'necro',      name: 'Necromancer Tower',   icon: '🗼', desc: 'The undead toil without rest',               baseCost: 2_000,      baseIncome: 7     },
  { id: 'plague',     name: 'Plague Well',         icon: '☣️', desc: 'Epidemics reap thousands of souls',          baseCost: 8_000,      baseIncome: 25    },
  { id: 'vampire',    name: 'Vampire Lair',        icon: '🦇', desc: 'Vampires drain souls every night',           baseCost: 30_000,     baseIncome: 80    },
  { id: 'forge',      name: 'Curse Forge',         icon: '⚒️', desc: 'Cursed weapons bring ruin',                 baseCost: 100_000,    baseIncome: 250   },
  { id: 'demonic',    name: 'Demonic Shrine',      icon: '😈', desc: 'Demons serve you faithfully',               baseCost: 350_000,    baseIncome: 750   },
  { id: 'hellgate',   name: 'Gates of Hell',       icon: '🌋', desc: 'Sinners\' souls flow endlessly from hell',   baseCost: 1_000_000,  baseIncome: 2_000 },
  { id: 'crypt',      name: 'Ancient Crypt',       icon: '🏛️', desc: 'Millennial spirits yield their savings',     baseCost: 3_000_000,  baseIncome: 6_000 },
  { id: 'castle',     name: 'Obsidian Castle',     icon: '🏰', desc: 'The heart of your dark empire',             baseCost: 10_000_000, baseIncome: 18_000 },
  { id: 'darkforest', name: 'Dark Forest',         icon: '🌲', desc: 'The forest is full of spirits and the lost', baseCost: 30_000_000, baseIncome: 50_000 },
  { id: 'swamp',      name: 'Shadow Swamp',        icon: '🌫️', desc: 'Shadows swallow wanderers without a trace',  baseCost: 100_000_000,baseIncome: 150_000 },
  { id: 'arena',      name: 'Monster Arena',       icon: '⚔️', desc: 'Monsters clash — the victor reaps the souls',baseCost: 300_000_000,baseIncome: 450_000 },
  { id: 'lab',        name: 'Mutant Laboratory',   icon: '🧪', desc: 'Mutants — the next step of darkness',        baseCost: 1e9,        baseIncome: 1_200_000 },
  { id: 'warlock',    name: 'Warlock Tower',       icon: '🧙', desc: 'Warlocks summon armies of spirits',          baseCost: 3e9,        baseIncome: 3_500_000 },
  { id: 'dragon',     name: 'Dragon Cave',         icon: '🐉', desc: 'The dragon burns cities — souls pour like rivers', baseCost: 10e9, baseIncome: 10_000_000 },
  { id: 'chaos',      name: 'Chaos Citadel',       icon: '🌀', desc: 'Chaos consumes reality — and souls with it', baseCost: 30e9,       baseIncome: 30_000_000 },
  { id: 'abyss',      name: 'Abyss of Oblivion',   icon: '🕳️', desc: 'The endless void demands sacrifices',        baseCost: 100e9,      baseIncome: 100_000_000 },
  { id: 'throne',     name: 'Throne of Darkness',  icon: '👑', desc: 'You are the absolute ruler. Darkness serves.', baseCost: 1e12,    baseIncome: 1_000_000_000 },
];
